name: Run parser
on:
  workflow_dispatch:
  schedule:
    - cron: "30 5 * * 5"
  push:
jobs:
  RunParser:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run parser
        shell: pwsh
        run: |
          ./main.ps1
      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Update data"
          git push
