name: Run parser
on:
  workflow_dispatch:
  schedule:
    - cron: "30 4 * * 5"
  push:
jobs:
  RunParser:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run parser
        shell: pwsh
        run: |
          try {
            ./main.ps1
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git add .
            git commit -m "Update data"
            git push
          }
          catch {
            write-host "No changes made"
          }
